repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Actualiza a la versión estable deseada.
    hooks:
      - id: black
        language_version: python3.7

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1  # Actualiza a la versión estable deseada.
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1  # Asegúrate de que la versión sea compatible con Black.
    hooks:
      - id: isort 